
name: dotnet build
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "release/*", "main" ]

  workflow_dispatch:

env:
  DOTNET_VERSION: 'v6.0.301' # The .NET SDK version to use

jobs:      
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Pull & update submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run: dotnet restore ./src/
      
    - name: Build
      run: dotnet build ./src/ --no-restore
