
name: Version Increment [PATCH]
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch: 

env:
  DOTNET_VERSION: 'v6.0.301' # The .NET SDK version to use

jobs:      
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      run: dotnet restore ./src/
      
    - name: Build
      run: dotnet build ./src/ --no-restore


  update-versions:
    name: update versions
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v23

    - name: Update all projects (with changed files) version minors
      shell: pwsh
      run: |
        ./src/incr_proj_patches.ps1 ${{ steps.changed-files.outputs.all_changed_files }}
        
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Increment version number(s)" -a
          
    - name: Push new versions
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: ${{ github.ref }}

