
name: Version Increment [PATCH]
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch: 

env:
  DOTNET_VERSION: 'v6.0.301' # The .NET SDK version to use

jobs:      
#  build:
#    name: build-${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest]
#    steps:
#    
#    - uses: actions/checkout@v3
#    - name: Setup .NET Core
#      uses: actions/setup-dotnet@v2.1.0
#      with:
#        dotnet-version: ${{ env.DOTNET_VERSION }}
#        
#    - name: Install dependencies
#      run: dotnet restore
#      
#    - name: Build
#      run: dotnet build ./src/ --no-restore


  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=ts::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .ts$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.all}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.all}}



